#!/bin/sh
set -C -f
case "$(file --dereference --brief --mime-type -- "$1")" in
	text/html ) lynx -width="$4" -display_charset=utf-8 -dump "$1"  ;;
	text/troff ) man ./ "$1" | col -b ;;
	text/* | */xml | application/json | application/javascript | application/x-setupscript ) bat --terminal-width "$4" -f "$1" ;;
	application/zip ) atool --list -- "$1" ;;
	application/x-7z-compressed ) atool --list -- "$1" ;;
	*opendocument* ) odt2txt "$1" ;;
	video/* | audio/* | application/octet-stream) mediainfo "$1" || exit 1 ;;
	application/pgp-encrypted) gpg -d -- "$1" ;;
esac
exit 1
